/* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// -----------------------------------------------
//
// This file is automatically generated
// Please do not edit these files manually
// Run the following in the root of the repos:
//
//      *NIX        :   ./build.sh codegen
//      Windows     :   build.bat codegen
//
// -----------------------------------------------

using System.Text.Json.Serialization;
using OpenSearch.Net.Specification.HttpApi;

namespace OpenSearch.Client;

public interface IHttpDeleteRequest : IArbitraryHttpRequest<HttpDeleteRequestParameters> { }

public class HttpDeleteRequest
    : ArbitraryHttpRequestBase<HttpDeleteRequestParameters>,
        IHttpDeleteRequest
{
    [SerializationConstructor, JsonConstructor]
    protected HttpDeleteRequest() { }

    public HttpDeleteRequest(string path)
        : base(path) { }
}

public interface IHttpGetRequest : IArbitraryHttpRequest<HttpGetRequestParameters> { }

public class HttpGetRequest : ArbitraryHttpRequestBase<HttpGetRequestParameters>, IHttpGetRequest
{
    [SerializationConstructor, JsonConstructor]
    protected HttpGetRequest() { }

    public HttpGetRequest(string path)
        : base(path) { }
}

public interface IHttpHeadRequest : IArbitraryHttpRequest<HttpHeadRequestParameters> { }

public class HttpHeadRequest : ArbitraryHttpRequestBase<HttpHeadRequestParameters>, IHttpHeadRequest
{
    [SerializationConstructor, JsonConstructor]
    protected HttpHeadRequest() { }

    public HttpHeadRequest(string path)
        : base(path) { }
}

public interface IHttpPatchRequest : IArbitraryBodyHttpRequest<HttpPatchRequestParameters> { }

public class HttpPatchRequest
    : ArbitraryBodyHttpRequestBase<HttpPatchRequestParameters>,
        IHttpPatchRequest
{
    [SerializationConstructor, JsonConstructor]
    protected HttpPatchRequest() { }

    public HttpPatchRequest(string path)
        : base(path) { }
}

public interface IHttpPostRequest : IArbitraryBodyHttpRequest<HttpPostRequestParameters> { }

public class HttpPostRequest
    : ArbitraryBodyHttpRequestBase<HttpPostRequestParameters>,
        IHttpPostRequest
{
    [SerializationConstructor, JsonConstructor]
    protected HttpPostRequest() { }

    public HttpPostRequest(string path)
        : base(path) { }
}

public interface IHttpPutRequest : IArbitraryBodyHttpRequest<HttpPutRequestParameters> { }

public class HttpPutRequest
    : ArbitraryBodyHttpRequestBase<HttpPutRequestParameters>,
        IHttpPutRequest
{
    [SerializationConstructor, JsonConstructor]
    protected HttpPutRequest() { }

    public HttpPutRequest(string path)
        : base(path) { }
}
